[global]
address = "0.0.0.0"
port = 8081
workers = 8
keep_alive = 5
secret_key = "this_is_just_for_demo"
limits = { forms = 32768 }

[global.tls]
certs = "./cert/cert.crt"
key = "./cert/unencrypted_key.pem"